SELECT d.DEPT_ID, d.DEPT_NAME_EN, s.AVG_SAL
FROM HR_DEPARTMENT d
JOIN (
    SELECT DEPT_ID, SUM(SAL), ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) s
ON d.DEPT_ID = s.DEPT_ID
ORDER BY s.AVG_SAL DESC;